# =============================================================================
# Dapr Secrets Component - Azure Key Vault
# =============================================================================
# This component configures Dapr to use Azure Key Vault for secrets management.
# Supports:
# - Managed Identity authentication (recommended)
# - Service Principal authentication
# - Workload Identity (AKS)
#
# Prerequisites:
# - Azure Key Vault created
# - AKS workload identity configured
# - Access policies set up for the managed identity
#
# Usage: Deploy to Kubernetes with: kubectl apply -f secrets-keyvault.yaml
# =============================================================================

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-keyvault
  namespace: todo-app
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    # Key Vault name
    - name: vaultName
      value: "${KEYVAULT_NAME}"

    # Azure AD tenant ID
    - name: azureTenantId
      value: "${AZURE_TENANT_ID}"

    # Client ID for authentication (Workload Identity)
    - name: azureClientId
      value: "${AZURE_CLIENT_ID}"

    # =======================================================================
    # Authentication Methods (choose one)
    # =======================================================================

    # Option 1: Workload Identity (Recommended for AKS)
    # No additional configuration needed if pod has workload identity annotation

    # Option 2: Service Principal with Client Secret
    # - name: azureClientSecret
    #   secretKeyRef:
    #     name: azure-sp-secrets
    #     key: client-secret

    # Option 3: Managed Identity (for Azure VMs/VMSS)
    # - name: azureEnvironment
    #   value: "AZUREPUBLICCLOUD"

# Scopes limit which applications can use this component
scopes:
  - todo-backend

---
# =============================================================================
# Service Account for Workload Identity
# =============================================================================
# This service account is annotated for Azure Workload Identity
# The AKS cluster must have OIDC issuer and workload identity enabled

apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-backend
  namespace: todo-app
  annotations:
    # Azure Workload Identity annotation
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
  labels:
    # Required label for workload identity
    azure.workload.identity/use: "true"

---
# =============================================================================
# Federated Identity Credential (created via Terraform/Azure CLI)
# =============================================================================
# This associates the Kubernetes service account with an Azure managed identity
#
# Azure CLI command:
# az identity federated-credential create \
#   --name todo-backend-federated \
#   --identity-name todo-backend-identity \
#   --resource-group ${RESOURCE_GROUP} \
#   --issuer ${AKS_OIDC_ISSUER} \
#   --subject system:serviceaccount:todo-app:todo-backend \
#   --audience api://AzureADTokenExchange

---
# =============================================================================
# Example: Pod Deployment with Workload Identity
# =============================================================================
# Example pod spec showing required labels and service account

# apiVersion: v1
# kind: Pod
# metadata:
#   name: todo-backend
#   namespace: todo-app
#   labels:
#     azure.workload.identity/use: "true"
# spec:
#   serviceAccountName: todo-backend
#   containers:
#     - name: todo-backend
#       image: ${ACR_NAME}.azurecr.io/todo-backend:latest
