apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
---
# Example Kubernetes Secret for application credentials
# Apply separately: kubectl apply -f secrets-k8s.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: default
type: Opaque
stringData:
  # Database connection string (Neon PostgreSQL)
  database-url: "postgresql+asyncpg://user:pass@host/db"
  # Better Auth secret for JWT verification
  better-auth-secret: "your-better-auth-secret-here"
  # Redis password (if authentication is enabled)
  redis-password: ""
  # Kafka credentials (for cloud deployment)
  kafka-username: ""
  kafka-password: ""
